# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c29597a2-353d-45fb-a6cc-a8e094fb50ca";
      fsType = "ext4";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/250fa407-b472-4e5e-aea5-6baf49345a80";
      fsType = "ext4";
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/d3fb29e2-cc1d-417c-baee-357c09e60ace";
      fsType = "ext4";
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/5be5239f-df5d-4eb6-a5b8-5e83aeb0257e";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/af9e5737-3f4f-4d24-8875-cdcd469e2f99";
      fsType = "ext4";
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/f9ecb886-a135-4ae5-a916-53fb26464484";
      fsType = "ext4";
    };

  fileSystems."/nfs1" =
    { device = "/dev/disk/by-uuid/177d514d-5c11-4fb0-a6e4-00f8253d47a2";
      fsType = "ext4";
    };

  fileSystems."/nfs0" =
    { device = "/dev/disk/by-uuid/85163606-467a-45df-869d-fc0c0f81f8ce";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7113-79B0";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/3864e317-c6f4-4506-aad9-dbb699c90a68"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
